# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVfnwsNczGPS8p13yR3CYiy539_fGt7p
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

startups= pd.read_csv('50_Startups.csv')

startups.head(5)

startups.drop(['State'], axis= 1, inplace= True)

startups.head(5)

X= startups.iloc[:,[0,1,2]].values
y= startups.iloc[:,3].values

regressor= LinearRegression()
regressor.fit(X,y)

pickle.dump(regressor, open('model.pkl', 'wb'))

model= pickle.load(open('model.pkl', 'rb'))
print(model.predict([[12000, 9000, 100000]]))

